version: "3"

includes:
  utils: taskfiles/utils.yml

env:
  ENV: local

tasks:
  run-utils:
    desc: Start Database
    dir: utils
    dotenv:
      - .env.local
    cmds:
      - docker compose up -d
