// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: add_book.sql

package database

import (
	"context"
	"database/sql"
)

const addBook = `-- name: AddBook :one
INSERT INTO books (title, authors, subjects, description, cover_art_url, work_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type AddBookParams struct {
	Title       string
	Authors     string
	Subjects    sql.NullString
	Description sql.NullString
	CoverArtUrl sql.NullString
	WorkID      string
}

func (q *Queries) AddBook(ctx context.Context, arg AddBookParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, addBook,
		arg.Title,
		arg.Authors,
		arg.Subjects,
		arg.Description,
		arg.CoverArtUrl,
		arg.WorkID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
