// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_book_by_id.sql

package database

import (
	"context"
)

const deleteBookByID = `-- name: DeleteBookByID :exec
DELETE FROM books WHERE id = $1 AND user_id = $2
`

type DeleteBookByIDParams struct {
	ID     int32
	UserID string
}

func (q *Queries) DeleteBookByID(ctx context.Context, arg DeleteBookByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteBookByID, arg.ID, arg.UserID)
	return err
}
