// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: delete_book_by_id.sql

package database

import (
	"context"
)

const deleteBookByID = `-- name: DeleteBookByID :exec
DELETE FROM books WHERE id = $1
`

func (q *Queries) DeleteBookByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteBookByID, id)
	return err
}
