// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_book_by_work_id.sql

package database

import (
	"context"
)

const getBookByWorkID = `-- name: GetBookByWorkID :one
SELECT id, title, authors, subjects, description, cover_art_url, work_id, user_id, status, rating, notes FROM books WHERE work_id = $1 AND user_id = $2
`

type GetBookByWorkIDParams struct {
	WorkID string
	UserID string
}

func (q *Queries) GetBookByWorkID(ctx context.Context, arg GetBookByWorkIDParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByWorkID, arg.WorkID, arg.UserID)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Authors,
		&i.Subjects,
		&i.Description,
		&i.CoverArtUrl,
		&i.WorkID,
		&i.UserID,
		&i.Status,
		&i.Rating,
		&i.Notes,
	)
	return i, err
}
