// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_book_by_work_id.sql

package database

import (
	"context"
)

const getBookByWorkID = `-- name: GetBookByWorkID :one
SELECT id, title, authors, subjects, description, cover_art_url, work_id FROM books WHERE work_id = $1
`

func (q *Queries) GetBookByWorkID(ctx context.Context, workID string) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByWorkID, workID)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Authors,
		&i.Subjects,
		&i.Description,
		&i.CoverArtUrl,
		&i.WorkID,
	)
	return i, err
}
