// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_book_by_id.sql

package database

import (
	"context"
)

const getBookByID = `-- name: GetBookByID :one
SELECT id, title, authors, subjects, description, cover_art_url, work_id, user_id, status, rating, notes FROM books WHERE id = $1 AND user_id = $2
`

type GetBookByIDParams struct {
	ID     int32
	UserID string
}

func (q *Queries) GetBookByID(ctx context.Context, arg GetBookByIDParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByID, arg.ID, arg.UserID)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Authors,
		&i.Subjects,
		&i.Description,
		&i.CoverArtUrl,
		&i.WorkID,
		&i.UserID,
		&i.Status,
		&i.Rating,
		&i.Notes,
	)
	return i, err
}
