// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Book struct {
	ID          int32
	Title       string
	Authors     string
	Subjects    sql.NullString
	Description sql.NullString
	CoverArtUrl sql.NullString
	WorkID      string
}
