// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_book.sql

package database

import (
	"context"
	"database/sql"
)

const updateBook = `-- name: UpdateBook :one
UPDATE books
SET status = $1,
    rating = $2,
    notes  = $3
WHERE id = $4 AND user_id = $5
RETURNING id, title, authors, subjects, description, cover_art_url, work_id, user_id, status, rating, notes
`

type UpdateBookParams struct {
	Status string
	Rating sql.NullInt32
	Notes  sql.NullString
	ID     int32
	UserID string
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, updateBook,
		arg.Status,
		arg.Rating,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Authors,
		&i.Subjects,
		&i.Description,
		&i.CoverArtUrl,
		&i.WorkID,
		&i.UserID,
		&i.Status,
		&i.Rating,
		&i.Notes,
	)
	return i, err
}
